#!/bin/bash
# =============================================================
#  dev:ending — Development Session Wrap-up
#  1. Update tasks.md (prompt user for completions)
#  2. Archive the change if everything is done
#  3. Write handover document for next developer
#  4. Push all changes to GitHub
# =============================================================

set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

HANDOVER_FILE="dev/handover.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
DATE=$(date '+%Y-%m-%d')
AUTHOR=$(git config user.name 2>/dev/null || echo "Unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "main")

echo ""
echo -e "${BOLD}${CYAN}🎯 Wrapping Up Development Session${RESET}"
echo -e "${CYAN}====================================${RESET}"
echo ""

# ── Load NVM ──────────────────────────────────────────────────
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# ── 1. Show Current Change Status ─────────────────────────────
echo -e "${BOLD}📊 [1/4] Active Changes${RESET}"
echo -e "${CYAN}─────────────────────────────────────────${RESET}"
ACTIVE_CHANGES=$(openspec list 2>/dev/null || echo "")
if [ -n "$ACTIVE_CHANGES" ]; then
  echo "$ACTIVE_CHANGES" | sed 's/^/  /'
else
  echo -e "  ${DIM}(no active changes)${RESET}"
fi
echo ""

# ── Ask what was accomplished ──────────────────────────────────
echo -e "${BOLD}📝 Session Summary${RESET}"
echo -e "${CYAN}─────────────────────────────────────────${RESET}"
echo -e "${YELLOW}What did you accomplish this session?${RESET}"
echo -e "${DIM}(Press Enter twice when done)${RESET}"
ACCOMPLISHED=""
while IFS= read -r line; do
  [ -z "$line" ] && break
  ACCOMPLISHED="${ACCOMPLISHED}\n- ${line}"
done

echo ""
echo -e "${YELLOW}What are the next steps?${RESET}"
echo -e "${DIM}(Press Enter twice when done)${RESET}"
NEXT_STEPS=""
while IFS= read -r line; do
  [ -z "$line" ] && break
  NEXT_STEPS="${NEXT_STEPS}\n- ${line}"
done

echo ""
echo -e "${YELLOW}Any blockers, notes, or important context?${RESET}"
echo -e "${DIM}(Press Enter twice when done, or just Enter to skip)${RESET}"
BLOCKERS=""
while IFS= read -r line; do
  [ -z "$line" ] && break
  BLOCKERS="${BLOCKERS}\n- ${line}"
done
[ -z "$BLOCKERS" ] && BLOCKERS="\n_None_"

echo ""

# ── 2. Archive Change If Complete ─────────────────────────────
echo -e "${BOLD}📦 [2/4] Archive Complete Changes${RESET}"
echo -e "${CYAN}─────────────────────────────────────────${RESET}"

if [ -n "$ACTIVE_CHANGES" ]; then
  echo -e "${YELLOW}Enter a change name to archive (or press Enter to skip):${RESET}"
  read -r CHANGE_NAME
  if [ -n "$CHANGE_NAME" ]; then
    echo -e "Checking status of '${BOLD}${CHANGE_NAME}${RESET}'..."
    openspec status --change "$CHANGE_NAME" 2>/dev/null || true
    echo ""
    echo -e "${YELLOW}Archive '${CHANGE_NAME}'? (y/N):${RESET} " && read -r ARCHIVE_CONFIRM
    if [[ "$ARCHIVE_CONFIRM" =~ ^[Yy]$ ]]; then
      if openspec archive "$CHANGE_NAME" 2>/dev/null; then
        echo -e "${GREEN}✅ Change '${CHANGE_NAME}' archived successfully!${RESET}"
      else
        echo -e "${YELLOW}⚠️  Could not archive — skipping${RESET}"
      fi
    else
      echo -e "${DIM}  Archive skipped.${RESET}"
    fi
  else
    echo -e "${DIM}  Archive skipped.${RESET}"
  fi
else
  echo -e "${DIM}  No active changes to archive.${RESET}"
fi
echo ""

# ── 3. Write Handover Document ────────────────────────────────
echo -e "${BOLD}📄 [3/4] Writing Handover Document...${RESET}"
mkdir -p dev

# Build active changes list for the doc
CHANGES_SNAPSHOT=$(openspec list 2>/dev/null || echo "_No active changes_")
LAST_COMMIT=$(git log -1 --format='`%h` %s (%ar)' 2>/dev/null || echo "_unknown_")

cat > "$HANDOVER_FILE" << HANDOVER
# 🔄 Development Handover

> **Last updated:** $TIMESTAMP
> **Author:** $AUTHOR
> **Branch:** \`$BRANCH\`

---

## ✅ Accomplished This Session

$(echo -e "$ACCOMPLISHED")

---

## ⏭️ Next Steps

$(echo -e "$NEXT_STEPS")

---

## ⚠️ Blockers / Notes

$(echo -e "$BLOCKERS")

---

## 📊 Project Status

### Active Changes
$CHANGES_SNAPSHOT

### Git
- **Last commit:** $LAST_COMMIT

---

## 🚀 How to Resume

\`\`\`bash
# Start next dev session
bash dev/startup.sh
\`\`\`

---
*Generated by \`dev/ending.sh\` — $TIMESTAMP*
HANDOVER

echo -e "${GREEN}✅ Handover document written to '${HANDOVER_FILE}'${RESET}"
echo ""
echo -e "${CYAN}─────────────────────────────────────────${RESET}"
cat "$HANDOVER_FILE"
echo -e "${CYAN}─────────────────────────────────────────${RESET}"
echo ""

# ── 4. Push to GitHub ─────────────────────────────────────────
echo -e "${BOLD}🚀 [4/4] Push to GitHub${RESET}"
echo -e "${CYAN}─────────────────────────────────────────${RESET}"
echo ""

# Stage all changes
git add -A
GIT_STATUS=$(git status --short)

if [ -n "$GIT_STATUS" ]; then
  echo -e "${BOLD}Files to commit:${RESET}"
  echo "$GIT_STATUS" | sed 's/^/  /'
  echo ""
  echo -e "${YELLOW}Push all changes to GitHub? (Y/n):${RESET} " && read -r PUSH_CONFIRM
  if [[ ! "$PUSH_CONFIRM" =~ ^[Nn]$ ]]; then
    git commit -m "chore: end-of-session update [$DATE]"
    git push origin "$BRANCH"
    echo -e "${GREEN}${BOLD}✅ All changes pushed to GitHub!${RESET}"
  else
    echo -e "${DIM}  Push skipped. Changes are staged but not committed.${RESET}"
    git restore --staged . 2>/dev/null || true
  fi
else
  echo -e "${DIM}  Nothing new to commit — repository is clean.${RESET}"
fi

echo ""
echo -e "${CYAN}════════════════════════════════════════════${RESET}"
echo -e "${GREEN}${BOLD}🎉 Session wrapped up successfully! See you next time 👋${RESET}"
echo -e "${CYAN}════════════════════════════════════════════${RESET}"
echo ""
